CREATE DATABASE IF NOT EXISTS `dbms-example`;
USE `dbms-example`;

CREATE TABLE IF NOT EXISTS `User` (
	UserId INT AUTO_INCREMENT,
	Email VARCHAR(255) NOT NULL,
	Name VARCHAR(255) NOT NULL,
	Password VARCHAR(255) NOT NULL,
	JoinDate TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT UC_Email UNIQUE(Email),
	PRIMARY KEY(UserId)
);

CREATE TABLE IF NOT EXISTS `Coupon` (
	CouponId INT AUTO_INCREMENT,
	Title VARCHAR(255) NOT NULL,
	Description TEXT,
	Brand VARCHAR(255),
	Location VARCHAR(255),
	DiscountStart TIMESTAMP NOT NULL,
	DiscountEnd TIMESTAMP NOT NULL,
	Currency VARCHAR(10),
	DiscountNum DECIMAL(10, 2) NOT NULL,
	DiscountType ENUM('percent', 'amount') NOT NULL,
	UploadDate TIMESTAMP DEFAULT NOW(),
	UploadedBy INT,
	Archived BOOLEAN DEFAULT FALSE,
	PRIMARY KEY(CouponId),
	CONSTRAINT FK_UploadedBy FOREIGN KEY (UploadedBy) REFERENCES `User`(UserId)
);
