CREATE DATABASE IF NOT EXISTS `dbms-example`;
USE `dbms-example`;

CREATE TABLE IF NOT EXISTS `User` (
	Id VARCHAR(20) NOT NULL,
	Account VARCHAR(50) NOT NULL,
	Name TEXT NOT NULL,
	Password TEXT NOT NULL,
	JoinAt TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY(Id)
);
